### ISSUE TITLE
NPE when connecting to native image

### ISSUE THREAD

**Issue by roberttoyonaga** [cryostatio/cryostat-core#217]
### Description of Bug
When Cryostat attempts connection to a native image executable a NPE is thrown. It is thrown because some RuntimeMXBean attributes are not applicable on SubstrateVM (ClassPath, LibraryPath, etc), but cryostat assumes they are non-null. [This is where the NPE happens.](https://github.com/cryostatio/cryostat-core/blob/84a69e9d1f7d0b3b2ea11d01fbef4690c7fcdaf2/src/main/java/io/cryostat/core/net/JFRJMXConnection.java#L223)

See error trace:
```
May 10, 2023 4:10:40 PM io.cryostat.core.log.Logger info
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10-131-1-71.robert-quarkus-insights.pod:9091/jmxrmi
May 10, 2023 4:10:40 PM io.cryostat.core.log.Logger error
SEVERE: Exception thrown
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "attrObject" is null
	at io.cryostat.core.net.JFRJMXConnection.getJvmId(JFRJMXConnection.java:223) 			***[ already connected] 
	at io.cryostat.net.TargetConnectionManager.lambda$executeConnectedTaskAsync$2(TargetConnectionManager.java:153)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
This was encountered on Scott's OpenShift cluster with the latest version of Cryostat. The native executable is a quarkus app. 

I don't remember this occurring the last time I tested cryostat with native image. But that was a few months ago, and I also wasn't testing with openshift. I'll see if I can reproduce the same problem locally and update this issue afterward.

**Comment by andrewazores** [comment]
The OpenShift part should not affect this code pathway, this should be fully reproducible locally with ex. the Cryostat `smoketest.sh` script.

What's happening is that when Cryostat discovers a JVM, it tries to connect to that JVM and hash some MBean attributes to generate a fingerprint ID of that JVM. It uses this fingerprint when doing things like storing archived recordings for that JVM, so that if you have two or more different URLs that resolve to the same actual JVM process, you can see the same data across those different URLs.

**Comment by andrewazores** [comment]
[The -agent also goes through this same code pathway](https://github.com/cryostatio/cryostat-agent/blob/8d2eb414029c436efde2c9b2d0a308d0dad59d66/src/main/java/io/cryostat/agent/MainModule.java#L274) when it's figuring out its fingerprint ID which it publishes to Cryostat when it does its discovery updates, so fixing this bug in `-core` will fix the problem on both sides.

**Comment by andrewazores** [comment]
@roberttoyonaga are there any other MBean attributes you think would make sense to add in to that hash? We could simply skip anything that is `null` and cannot be retrieved in cases like SubstrateVM, and then check that the `DataOutputStream` is not empty before hashing it (and throw some informative exception if it is empty), but I worry that eliminating too many of these attributes may lead to hash collisions in practice because there just isn't enough input differentiation.

**Comment by roberttoyonaga** [comment]
> are there any other MBean attributes you think would make sense to add in to that hash

Hmm maybe you could try OperatingSystemMXBean.Arch, OperatingSystemMXBean.Name, RuntimeMXBean.Pid, RuntimeMXBean.SpecVersion, RuntimeMXBean.VmName.  I just tried these out on quarkus native connecting with JMC.  These are all non-null and constant for the life of the process in SubstrateVM.

**Comment by andrewazores** [comment]
Yea, that's one of the key ones for sure, though it's "only" millisecond resolution and so I wonder if it can still be a problem in a container orchestration environment where a deployment is scaled up and several replicas are started. I suppose it depends heavily on the cluster/node doing that work, but might more than one container come up with the same millisecond timestamp? Hmm.

**Comment by roberttoyonaga** [comment]
Right, that's a good point. In that sort of scenario most of the other attributes will be shared as well :(

**Comment by andrewazores** [comment]
Yep, that's what I thought when I was originally working with Janelle to implement this hashing technique. I don't think the JVM generally has any exposed unique ID like this, at least not one that we can retrieve over JMX/MBean. Even the PID isn't likely to be helpful in containers.

I wonder if the hostname or primary interface IP can be pulled from somewhere?

**Comment by roberttoyonaga** [comment]
> I wonder if the hostname or primary interface IP can be pulled from somewhere?

Not sure about this. Off the top of my head I haven't seen anywhere this might be accessible via RJMX.

**Comment by andrewazores** [comment]
Otherwise, if this is not fully solvable in the case where Cryostat determines the fingerprint ID by connecting to the JVM over JMX, it's still solvable in the case where the Agent is present and determines its own ID to publish to Cryostat. We can just forego the whole MBean attribute collection stuff there and simply generate a UUID.

**Comment by mwangggg** [comment]
By skipping attributes that are null, I am able to see the GraalVM native image in the topology view. However, a new error presents itself after selecting it as the target in the recordings view: 

![Screenshot from 2023-05-25 13-44-51](https://github.com/cryostatio/cryostat-core/assets/90855268/456fda64-70bb-4f39-971c-bdd311a8458c)

**Comment by andrewazores** [comment]
I think there should be a longer/more informative corresponding stack trace in the Cryostat server logs when that happens. Could you post it here as well?

**Comment by andrewazores** [comment]
Actually, you could post that in the PR you've opened.
